name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Change directory
        run: cd ./links-preparer

      - name: Install dependencies
        run: npm install
        working-directory: ./links-preparer

      - name: Build
        run: npm run build
        working-directory: ./links-preparer

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./links-preparer/dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./links-preparer/dist
